language: node_js

node_js:
  - 8.5.0

sudo: false

before_install:
  - sudo apt-get -qq update

install:
  - npm install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run build
  - npm run live &
  - sleep 5 # give server time to start

#before_script:

script:
  - env
  - ls -1 web
  - node ./tests/travisWebdriverioTest.js

branches:
  only:
    - feature-add-travis-support

addons:
  sauce_connect:
    username: webdevel
  jwt:
    secure: SWs3TjOO7qNEOQJGXP629Qh+rcHW2YX6602mdqy1+sqCdS4jmns2cliHokU66kA5VLjjV9Ccv6A0EclTekcuoKvq2GWKETGmTT1nkRlMumVK8vkM44b3EzHExwUPbieDS0ZbIxoNPloslNxKX7deEWNw3UdsQZEMKpM9LWbNKCVU2OVLsp3Dcn3wvooCsXjSkT4QrOb4uSohlpB5av8mohm80uDEhv62sqzK+NzaieNoUAJoiHaKR8eFv7SzNQemzaxhVcRMf2+LP9KB7fadp7JT2yv7IHI/12Hy01PlEYIzQldqzaZwb1b9ciy12RydaXDIf1dlrWs3yCphrtp5dyLA8u+udvMoU0D9ybpjveM/Q4YzfZh5zgyeUSZVJzMr1+LzcymG/Vl3DEkw4A5GPoR0/EnkQFdWmLoXD2s9Cnf5c+1r7M75iEldRjZVxvqFgzrqf6V9eLm+wh2nW7vMxlktNVu8P4PJzqWePvJIcwqEtlQM4YoYNwGcvRl+fhe/Z6/xFSFYXpKs5sYEZsWyi1/CdgXVrPnY7oIzz9U2usOr1tD4FXK+mhOgaJsR++1f4Fx8VqD4RAUPFusFNSA2nkX31noMc2IBHTM+oUMN6VyLfKUPB7vDFMUwW9ZL1lJcVTvMy5YLoEFLQuurSSf5zJDobZaYZh63jfUnYrz9/XI=
